### ISSUE TITLE
Blue Shift not working

### ISSUE THREAD

**Issue by qabRieL99** [hzqst/CaptionMod#3]
Launching Blue Shift with the mod enabled causes game to crash without any errors. Apparently the font file is still in use since it cannot be deleted.

**Comment by hzqst** [comment]
![image](https://user-images.githubusercontent.com/12287588/80778592-8a050d00-8b9b-11ea-8403-e1dd2f38d0bf.png)

![image](https://user-images.githubusercontent.com/12287588/80778637-a7d27200-8b9b-11ea-88b0-3768d7d20544.png)


![image](https://user-images.githubusercontent.com/12287588/80778340-ac4a5b00-8b9a-11ea-9432-267d6c37f90d.png)

it seems that bshift client failed to get VGUI_ivgui006 interface, I am looking into it further.

**Comment by hzqst** [comment]
The problem comes when we install hook for GetProcAddress and returns our CreateInterface instead of client.dll's one

Our CreateInterface gives NULL when bshift request for VGUI_ivgui006 interface.
I have removed the GetProcAddress hook and everything works fine playing latest bshift (steam 8303).

https://github.com/hzqst/CaptionMod/blob/0a7f32e33a1c6d30da5e65a2e0a8c38b815ed147/MetaHook/Plugins/CaptionMod/BaseUI.cpp#L153

**Comment by qabRieL99** [comment]
Thank you. It works with Blue-Shift in latest version (which is 8308 by the way), but this time it doesn't work with rest of the games (HL, OP, Decay.) Is there anyway we can have it all of them working?

**Comment by hzqst** [comment]
> Thank you. It works with Blue-Shift in latest version (which is 8308 by the way), but this time it doesn't work with rest of the games (HL, OP, Decay.) Is there anyway we can have it all of them working?

latest commit should fix the HL and OP crash.
