### ISSUE TITLE
Support for other letters

### ISSUE THREAD

**Issue by qabRieL99** [hzqst/CaptionMod#5]
All letters work fine in subtitles, but they get broke mid-word. An example is "Ö" letter.
Ödipuskonflikt is divided as 
Ö
"newline"
dipuskonflikt

**Comment by hzqst** [comment]
Ö is not treated as English letter due to https://github.com/hzqst/CaptionMod/blob/36ca12818e945cd67bbb06d5cace5d8021af7c16/MetaHook/Plugins/CaptionMod/SubtitlePanel.cpp#L411
It seems the "Ö" is a non-ascii char (with non-zero first byte as an unicode char), could you provide a list of non-ascii unicode chars that should be treated as English letters ?

**Comment by qabRieL99** [comment]
In my case, they're: Ç ç Ğ ğ İ ı Ö ö Ş ş Ü ü

**Comment by qabRieL99** [comment]
This can be solved by adding them manually.
